### ISSUE TITLE
SQL Error with Visibility

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Pin-Post#12]
![bug1](https://user-images.githubusercontent.com/778890/106010085-5b2faf00-60b9-11eb-99e9-3696d7d5d6f6.jpg)

![bug2](https://user-images.githubusercontent.com/778890/106010157-6c78bb80-60b9-11eb-87f9-09a8439f308b.jpg)

@effone

**Comment by effone** [comment]
@Sama34 Help on the logic?

**Comment by effone** [comment]
https://github.com/mybbgroup/Pin-Post/blob/b7abbfbd148210e32b4a63d98425fa004b3835b9/upload/inc/plugins/pinpost.php#L242

Probably this should be `if($visible && is_string($visible))` ?

**Comment by Sama34** [comment]
I don't know why I did pick `$visible` so I pushed a different approach.
